### ISSUE TITLE
Can't alter int value properly

### ISSUE THREAD

**Issue by rilpires** [Stoeoeoe/godot_data_editor#3]
I'm writting a new value for an int property, I even press enter, but when I save it returns to the previous value. I can still alter string values tho

**Comment by rilpires** [comment]
nevermind actually I'm still figuring what exactly is the problem

**Comment by Stoeoeoe** [comment]
Hi, thanks for the report! Probably there is some issue with the control. Did you use any hints, e.g. constraining the value?

**Comment by rilpires** [comment]
I dont know if this is intentional (I guess not) but what was happening is that I couldn't set int values higher than 100, unless I set by export hint:

```
#Can't set values > 100:
export (int) var int_value

#Can set values > 100:
export ( int , 0 , 1000000 ) var int_value 
```
