### ISSUE TITLE
engine.cfg resetting when reopening project

### ISSUE THREAD

**Issue by rilpires** [Stoeoeoe/godot_data_editor#4]
When I close and reopen the project, some project settings resets (input actions and autoloads for example). 

The problem is only with engine.cfg, because if I keep a backup copy and replace it while with the editor open, it works normally.

Also if I disable the plugin in project settings, It works fine too (engine.cfg saves properly).

**Comment by Stoeoeoe** [comment]
Thanks again, I will look into it this evening - should be easy to fix. Actually, the engine.cfg should only be loaded and a setting should be added. But this whole engine.cfg reconfiguration is quite flimsy anyway and I'm thinking of removing it. Sorry that you lost the cfg.

**Comment by Stoeoeoe** [comment]
Hi, I looked into it and I really don't understand what's going on. The engine behaves totally weird. I think the engine.cfg is not really happy when I make changes to it, so I just removed the part that attempts to insert the data singleton.
I added instructions to the readme.

Could you download the newest version and check if the problem still occurs?

**Comment by rilpires** [comment]
Now it works fine, no problem
Nice work there on the plugin btw, I found it very useful for my project

**Comment by Stoeoeoe** [comment]
Thanks, I will close the issue.
