### ISSUE TITLE
Globals.set("name", object) in Godot 3?

### ISSUE THREAD

**Issue by PLyczkowski** [Stoeoeoe/godot_data_editor#8]
I saw you use Globals.set("name", object) in the plugin, which looks very handy - do you know how to replicate that functionality in Godot 3? Globals seem to have been replaced with ProjectSettings, but you can't store objects with that anymore..

**Comment by Stoeoeoe** [comment]
Hi, 
I just started looking into Godot 3 a few days ago. I've also seen that Globals have been replaced with ProjectSettings and just assumed that it would work the same. 

I tried out the following code and it worked:

```GDScript
extends Node2D


func _ready():
	var some_node = Node.new()
	ProjectSettings.set("node", some_node)
	print(str(ProjectSettings.get("node")))
	
	var some_object = Button.new()
	some_object.text = "Hello World"
	ProjectSettings.set("object", some_object)
	print(some_object.text)
```

The output was `[Node:948]` and `Hello World`, so I guess I will be using the same approach when I port the addon to 3.0! :)
Although I still feel that this way is rather hacky.
